# Generated by Django 4.2.10 on 2024-02-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('paid_summ', models.FloatField(verbose_name='paid_summ')),
                ('payment_method', models.CharField(choices=[('CASH', 'paid by cash'), ('CARD', 'paid by card')], max_length=10, verbose_name='paid_type')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materials.course', verbose_name='paid_course')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materials.lesson', verbose_name='paid_lesson')),
            ],
        ),
    ]
