# Generated by Django 4.2.10 on 2024-02-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='services_id',
            field=models.CharField(default=123, max_length=200, verbose_name='services_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='success_url',
            field=models.CharField(default=123, max_length=400, verbose_name='success_url'),
            preserve_default=False,
        ),
    ]
